version: 2.1

jobs:
  build-learning-javascript:
    working_directory: ~/learning-javascript
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-javascript-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-javascript-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: npm run build
